active-mq:
    broker-url: tcp://localhost:61616
    topic: demo321
    queue: demoqueue
    
spring.datasource:
    url: jdbc:mysql://localhost:3306/demo_schema
    username: root
    password: password    