active-mq:
    broker-url: tcp://localhost:61616
    name:
        outward-queue: DEMO_OUTWARD_QUEUE
        inward-queue: DEMO_INWARD_QUEUE
    concurrency:
        outward-queue: 2-2
        inward-queue: 2-2
    
spring.datasource:
    url: jdbc:mysql://localhost:3306/demo_schema
    username: root
    password: password